# Generated by Django 3.0.5 on 2020-05-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
