# Generated by Django 3.0.5 on 2020-05-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_time_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='first',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='last',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
