# Generated by Django 3.0.5 on 2020-05-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200506_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='location',
            new_name='away',
        ),
        migrations.AddField(
            model_name='time',
            name='home',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
