# Generated by Django 3.0.5 on 2020-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200506_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='coach',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
