# Generated by Django 3.0.5 on 2020-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_time_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='focus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
